adminapp/urls.py
from django.urls import path
import adminapp.views as adminapp

app_name = 'adminapp'

urlpatterns = [
    path('', adminapp.MainView.as_view(), name='main_admin'),
    path('users/', adminapp.UserListView.as_view(), name='users'),
    path('users/create/', adminapp.UserCreateView.as_view(), name='user_create'),
    path('users/update/<int:pk>/', adminapp.UserUpdateView.as_view(), name='user_update'),
    path('users/delete/<int:pk>/', adminapp.UserDeleteView.as_view(), name='user_delete'),

    path('categories/create/', adminapp.CategoryCreateView.as_view(), name='category_create'),
    path('categories/', adminapp.CategoryListView.as_view(), name='categories'),
    path('categories/update/<int:pk>/', adminapp.CategoryUpdateView.as_view(), name='category_update'),
    path('categories/delete/<int:pk>/', adminapp.CategoryDeleteView.as_view(), name='category_delete'),

    path('articles/create/', adminapp.ArticleCreateView.as_view(), name='article_create'),
    path('articles/', adminapp.ArticlesListView.as_view(), name='articles'),
    path('articles/update/<uuid:pk>/', adminapp.ArticleUpdateView.as_view(), name='article_update'),
    path('articles/delete/<uuid:pk>/', adminapp.ArticleDeleteView.as_view(), name='article_delete'),

    path('comments/create/', adminapp.CommentCreateView.as_view(), name='comment_create'),
    path('comments/', adminapp.CommnetsListView.as_view(), name='comments'),
    path('comments/update/<int:pk>/', adminapp.CommentUpdateView.as_view(), name='comment_update'),
    path('comments/delete/<int:pk>/', adminapp.CommentDeleteView.as_view(), name='comment_delete'),

    path('news/', adminapp.NewsListView.as_view(), name='news'),
    path('news/create/', adminapp.NewsCreateView.as_view(), name='news_create'),
    path('news/update/<int:pk>/', adminapp.NewsUpdateView.as_view(), name='news_update'),
    path('news/delete/<int:pk>/', adminapp.NewsDeleteView.as_view(), name='news_delete'),

    path('moder/', adminapp.ModerListView.as_view(), name='moder'),
    path('moder/article/<uuid:pk>/', adminapp.ApproveArticle.as_view(), name='approve_article'),
    path('moder/news/<int:pk>/', adminapp.ApproveNews.as_view(), name='approve_news'),
    path('moder/notify/delete/<int:pk>/', adminapp.NotifyDeleteView.as_view(), name='notify_delete'),
    path('moder/block/<int:pk>', adminapp.UserBlock.as_view(), name='user_block'),
]

articleapp/urls.py
from django.urls import path
from articleapp.views import IndexView, ArticleDetailView, \
    ArticleCreateView, ArticleUpdateView, ArticleDeleteView, like_art, \
    CategoryArticleView, ArticleListView, ArticlePublished


app_name = 'articleapp'

urlpatterns = [
    path('', IndexView.as_view(), name='main'),
    path('index/', IndexView.as_view(), name='main'),
    path('article/new/', ArticleCreateView.as_view(), name='add'),
    path('article/list/', ArticleListView.as_view(), name='list'),
    path('article/<uuid:pk>/', ArticleDetailView.as_view(), name='detail'),
    path('article/<uuid:pk>/edit/', ArticleUpdateView.as_view(), name='edit'),
    path('article/<uuid:pk>/delete/', ArticleDeleteView.as_view(),
         name='delete'),
    path('article/<uuid:pk>/like/', like_art, name='like-art'),
    path('article/category/<int:pk>', CategoryArticleView.as_view(), name='article_category'),
    path('article/<uuid:pk>/published/', ArticlePublished.as_view(), name='public'),
]

authapp/urls.py
from django.urls import path
from .views import LoginUserView, LogoutUserView, RegisterUserView, VerifyView, ProfileEditView, UserDetailView, \
    UserChangePassword
from django.conf.urls import include, url

app_name = 'authapp'

urlpatterns = [
    path('login/', LoginUserView.as_view(), name='login'),
    path('logout/', LogoutUserView.as_view(), name='logout'),
    path('register/', RegisterUserView.as_view(), name='register'),
    path('edit/<int:pk>/', ProfileEditView.as_view(), name='edit'),
    path('verify/<email>/<activation_key>', VerifyView.as_view(), name='verify'),
    path('profile/<int:pk>', UserDetailView.as_view(), name='profile'),
    path('change-password/', UserChangePassword.as_view(), name='change_pass'),
]

habrband/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static
from mainapp.views import about, help

urlpatterns = [
    path('admin/', admin.site.urls),
    path('_admin/', include('adminapp.urls', namespace='_admin')),
    path('temp/', include('mainapp.urls')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('news/', include('news.urls', namespace='news')),
    path('', include('articleapp.urls', namespace='article')),
    path('', include('social_django.urls', namespace='social')),
    path('', include('searchapp.urls', namespace='search')),
    path('notification/', include('notificationapp.urls', namespace='notify')),
    path('about/', about, name='about'),
    path('help/', help, name='help'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/urls.py
from django.urls import path
from . import views
app_name = 'news'

urlpatterns = [
    path('', views.NewsListView.as_view(), name='main'),
    path('create_news', views.NewsCreateView.as_view(), name='create_news'),
    path('<int:pk>', views.NewsDetailView.as_view(), name='news_detail'),
    path('<int:pk>/update', views.NewsUpdateView.as_view(), name='news_update'),
    path('<int:pk>/delete', views.NewsDeleteView.as_view(), name='news_delete')
]

articleapp/models.py
from uuid import uuid4
from django.db import models
from django.urls import reverse
from authapp.models import HabrUser
from ckeditor.fields import RichTextField
from commentapp.middleware import get_current_user


class FilterArticle(models.Manager):
    """
    класс - Фильтр статей
    """
    def get_queryset(self):
        """
        :return:
        """
        user = get_current_user()
        if user is not None and not user.is_authenticated:
            return super().get_queryset().filter(approve=True)
        elif user is not None and user.is_staff:
            return super().get_queryset().filter(
                models.Q(approve=True) |
                models.Q(approve=False))
        return super().get_queryset().filter(
            models.Q(approve=True,
                     author=get_current_user()) |
            models.Q(approve=True))


class Category(models.Model):
    """
    класс - Категории
    """
    name = models.CharField(max_length=200)
    is_active = models.BooleanField(default=True, null=False)

    def __str__(self):
        return self.name

    class Meta:
        """
        класс - Мета
        """
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def delete(self, using=None, keep_parents=False):
        """
        :param using:
        :param keep_parents:
        :return:
        """
        self.is_active = False if self.is_active else True
        self.save()


class Article(models.Model):
    """
    класс - Статьи
    """
    DRAFT = 'DF'
    PUBLISHED = 'PB'
    DELETED = 'DT'
    STATUSES = (
        (DRAFT, 'черновик'),
        (PUBLISHED, 'опубликованный'),
        (DELETED, 'удалённый'),
    )
    uid = models.UUIDField(verbose_name='Ид', primary_key=True, default=uuid4)
    title = models.CharField(max_length=200, verbose_name='Заголовок')
    content = RichTextField(verbose_name='Текст', blank=True, null=True)
    author = models.ForeignKey(HabrUser, on_delete=models.DO_NOTHING,
                               verbose_name="Автор")
    category = models.ForeignKey(Category, blank=True, null=True,
                                 on_delete=models.DO_NOTHING,
                                 verbose_name="Категория")
    created = models.DateTimeField(auto_now_add=True, verbose_name='Создан')
    updated = models.DateTimeField(auto_now=True, verbose_name='Обновлен')
    image = models.ImageField(upload_to='article_photos/', blank=True,
                              null=True, verbose_name='Изображение')
    status = models.CharField(choices=STATUSES, max_length=128, default='DF')
    liked = models.ManyToManyField(HabrUser, blank=True, related_name='likes')
    approve = models.BooleanField('Модерация', default=False)
    publication_date = models.DateTimeField(verbose_name='Дата публикации',
                                            blank=True, null=True)
    # objects = FilterArticle()

    def __str__(self):
        """
        :return:
        """
        return self.title

    class Meta:
        """
        класс - Мета
        """
        ordering = ('-created',)
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'

    def get_absolute_url(self):
        """
        :return:
        """
        return reverse('article:detail', args=[self.uid])

    def delete(self, using=None, keep_parents=False):
        """
        :param using:
        :param keep_parents:
        :return:
        """
        self.status = 'DT' if self.status != 'DT' else 'DF'
        self.approve = False

        self.save()

    @property
    def num_likes(self):
        """
        :return:
        """
        return self.liked.all().count()


class Like(models.Model):

    LIKE = 'Like'
    DISLIKE = 'Like'

    LIKE_CHOICES = (
        (LIKE, 'Like'),
        (DISLIKE, 'Dislike')
    )

    """
    класс - Лайки
    """
    user = models.ForeignKey(HabrUser, on_delete=models.CASCADE)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    value = models.CharField(choices=LIKE_CHOICES, default=LIKE,
                             max_length=8)

    def __str__(self):
        """
        :return:
        """
        return str(self.article)

articleapp/forms.py
from django.forms import ModelForm
from adminapp.forms import add_class_html
from articleapp.models import Article


class ArticleForm(ModelForm):
    """
    класс - Форма для статей
    """
    class Meta:
        """
        класс - Мета
        """
        model = Article
        fields = ('title', 'category', 'content', 'image')

    def __init__(self, *args, **kwargs):
        super(ArticleForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ArticleApprove(ModelForm):
    """
    класс - Модерация статей
    """
    class Meta:
        """
        класс - Мета
        """
        model = Article
        exclude = ['uid', 'title', 'content', 'author', 'category',
                   'created', 'updated', 'image', 'status', 'liked', 'objects']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        add_class_html(self.fields)

articleapp/views.py
from django.http import JsonResponse, HttpResponseRedirect
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, \
    DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import FormMixin

from articleapp.forms import ArticleForm, ArticleApprove
from articleapp.models import Article, Like, Category
from commentapp.forms import CommentsForm
from commentapp.views import CommentView
from mainapp.views import main
from ratingapp.models import ArticleRating
from ratingapp.queryset import add_rating
from .mixins import UserIsNoBlockMixin

# Отображение содержимого из модели Article
class IndexView(ListView):
    """
    класс - Index
    """
    queryset = add_rating(Article.objects.filter(approve=True))
    paginate_by = 4
    template_name = 'mainapp/index.html'
    ordering = ('-publication_date', '-created')


# Отображение списка статей
class ArticleListView(ListView):
    """
    класс - ArticleList
    """
    model = Article
    paginate_by = 5
    template_name = 'articles_list.html'

    def get_queryset(self):
        """
        :return:
        """
        return Article.objects.filter(author=self.request.user)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)

        context['object_list'] = add_rating(context['object_list'])

        return context


# Отображение содержимого
class ArticleDetailView(CommentView, FormMixin, DetailView):
    """
    класс - ArticleDetail
    """
    model = Article
    form_class = CommentsForm
    second_form_class = ArticleApprove
    template_name = 'article_detail.html'

    def get_context_data(self, **kwargs):
        """
        :param kwargs:
        :return:
        """
        context = super(ArticleDetailView, self).get_context_data(**kwargs)
        if 'form' not in context:
            context['form'] = self.form_class(instance=self.object.comments)
        if 'form2' not in context:
            context['form2'] = self.second_form_class(instance=self.object)

        try:
            rating = get_object_or_404(ArticleRating, article=self.object)
            context['rating'] = rating.value()
        except Exception:
            # TODO обработать конкретное исключение
            context['rating'] = 0

        return context


class ArticleCreateView(LoginRequiredMixin, CreateView):
    """
    класс - ArticleCreate
    """
    model = Article
    template_name = 'article_new.html'
    form_class = ArticleForm

    def post(self, request, *args, **kwargs):
        """
        :param request:
        :param args:
        :param kwargs:
        :return:
        """
        form = self.get_form()
        if form.is_valid():
            article = form.save(commit=False)
            article.author = request.user
            self.object = article.save()
            return redirect('auth:profile', request.user.pk)

        return self.form_invalid(form)


class ArticleUpdateView(UserIsNoBlockMixin, UpdateView):
    """
    класс - ArticleUpdate
    """
    model = Article
    template_name = 'article_edit.html'
    fields = ['title', 'category', 'content', 'image']


class ArticleDeleteView(UserIsNoBlockMixin, DeleteView):
    """
    класс - ArticleDelete
    """
    model = Article
    template_name = 'article_delete.html'
    success_url = reverse_lazy(main)


class ArticlePublished(UserIsNoBlockMixin, DeleteView):
    """
    класс - Публикация статьи
    """
    model = Article

    def get_success_url(self):
        return self.request.META.get('HTTP_REFERER')

    def delete(self, request, *args, **kwargs):
        """  """
        self.object = self.get_object()
        success_url = self.get_success_url()
        self.object.status = 'PB'
        self.object.save()
        return HttpResponseRedirect(success_url)


def like_art(request, pk):
    """
    :param request:
    :param pk:
    :return:
    """
    user = request.user
    if request.method == 'POST':
        article_id = request.POST.get('article_id')
        article_obj = Article.objects.get(pk=article_id)

        if user in article_obj.liked.all():
            article_obj.liked.remove(user)
        else:
            article_obj.liked.add(user)
        like, created = Like.objects.get_or_create(user=user,
                                                   article_id=article_id)
        if not created:
            if like.value == 'Like':
                like.value = 'Dislike'
            else:
                like.value = 'Like'
        else:
            like.value = 'Like'

            article_obj.save()
            like.save()

        data = {
            'value': like.value,
            'likes': article_obj.liked.all().count()
        }
        return JsonResponse(data, safe=False)

    return redirect('article:detail', pk=pk)


class CategoryArticleView(ListView):
    """
    класс - Сортировка статей по категориям
    """
    model = Article
    template_name = 'category.html'
    paginate_by = 6

    def get_queryset(self):
        """
        :return:
        """
        self.category = get_object_or_404(Category, pk=self.kwargs['pk'])

        queryset = Article.objects.filter(category=self.category)\
            .filter(status='PB', approve=True)
        queryset = add_rating(queryset)
        return queryset

    def get_context_data(self, **kwargs):
        """
        :param kwargs:
        :return:
        """
        context = super(CategoryArticleView, self).get_context_data(**kwargs)
        context['category'] = self.category
        return context

articleapp/templates/article_delete.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}
    <h1>Удалить статью</h1>
    <form action="" method="post">{% csrf_token %}
        <p>Вы уверены, что хотите удалить статью "{{ article.title }}"?</p>
        {{ form.as_p }}
        <input type="submit" value="Confirm" />
    </form>
{% endblock content %}

articleapp/templates/article_detail.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}

<section id="blog" class="blog">
    <div class="container">
        <div class="article-edit-form">   

            <div class="post-entry">
                <h2>{{ article.title }}</h2>
                <p>
                    <i class="bi bi-person"></i>
                    <a href="{% url 'auth:profile' article.author.pk %}" target="_blank">{{ article.author }}</a>
                </p>
                <p>
                    <i class="bi bi-clock"></i>
                    {% if article.status == 'PB' and article.approve %}
                    <a>{{ article.publication_date }}</a>
                    {% else %}
                        {% if not article.updated == '' %}
                        <a>{{ article.updated }}</a>
                        {% else %}
                        <a>{{ article.created }}</a>
                        {% endif %}
                    {% endif %}
                </p>
                <p>
                    <i class="bi bi-bar-chart"></i>
                    Рейтинг: {{ rating }}
                </p>
                <p>{{ article.category }}</p>
                <p>{{ article.content | safe }}</p>
                {#<p>{{ article.image }}</p>#}
            </div>
            {% if request.user == article.author and not request.user.check_block %}
            <div class="row">
                <div class="col-sm-2 d-flex justify-content-center">
                    <a class=" btn btn-secondary btn-block w-100" style="background-color: #e96b56; border-color: #e96b56;"
                       href="{% url 'article:edit' article.pk %}">Редактировать</a>
                </div>
                {% if article.status != 'DT'%}
                <div class="col-sm-2 d-flex justify-content-center">
                    <a class="btn btn-secondary btn-block w-100" style="background-color: #e96b56; border-color: #e96b56;"
                       href="{% url 'article:delete' article.pk %}">Удалить</a>
                </div>
                {% endif %}
                {% if article.status == 'DF' %}
                <div class="col-sm-2 d-flex align-items-center ">
                    <form method="POST" class="w-100 mar-b-5" action="{% url 'article:public' article.pk %}">
                        {% csrf_token %}
                        <input class="btn btn-secondary btn-block w-100 d-flex justify-content-center" type="submit"
                            style="background-color: #e96b56; border-color: #e96b56;" value="Опубликовать">
                    </form>
                </div>
                {% endif %}
            </div>
            {% endif %}
            <hr/>
            {% if request.user.is_authenticated and request.user.role != 'U' %}
            <div class="row">
                <div class="col-sm-2 d-flex align-items-end" style="margin-bottom:10px">Для администраторов:</div>
                {% if request.user.role == 'A' or request.user.is_superuser %}
                <div class="col-sm-2">
                    <a href="{% url '_admin:article_update' article.pk %}"
                       class="btn btn-outline-secondary btn-block align-items-start d-b h-100 w-100">Редактировать</a>
                </div>
                {% endif %}
                <div class="col-sm-2">
                    <form method="POST" action="{% url '_admin:article_delete' article.pk %}">
                        {% csrf_token %}
                        <input class="btn btn-outline-secondary btn-block align-items-end d-b w-100"
                               type="submit"
                               value="{% if article.status != 'DT' %} Удалить {% else %} restore {% endif %}">
                    </form>
                </div>
            </div>
            <hr/>
            {% endif %}
            <div class="d-flex row div_like" style="margin-top: 10px; margin-bottom: 10px;">
                {% if not request.user.check_block and request.user.is_authenticated %}
                <div class="col-sm-12">
                    <form action="{% url 'article:like-art' article.pk %}" method="POST" class="like-form"
                            id="{{article.pk}}">
                        {% csrf_token %}
                        <input type="hidden" name="article_id" value="{{article.pk}}">
                        <button type="submit" class="btn btn-success btn-sm like-btn{{article.pk}}">
                        {% if user not in article.liked.all %}Нравится{% else %}Не нравится{% endif %}
                        </button>
                    </form>
                </div>
                {% endif %}
                <br>
                <div class="col-sm-12">
                    <div class="fa fa-thumbs-up like-count{{article.pk}}" style="font-size: 21px; margin-top: 5px;">
                         {{ article.liked.all.count }}
                    </div>
                </div>
            </div>
            <hr>
            {% include "include_comments.html" %}
        </div>
    </div>
</section>
{% endblock content %}

{%block js%}
<script src="{% static 'assets/js/like.js' %}"></script>
{%endblock%}

articleapp/templates/article_edit.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}
    <section id="blog" class="blog">
        <div class="container">
            <div class="article-edit-form"><h4>Редактировать статью</h4>
                <form action="" method="post">
                    {% csrf_token %}
                    {{ form.media | safe }}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">Редактировать</button>
                </form>
            </div>
        </div>
    </section>
{% endblock content %}

articleapp/templates/article_new.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}
    <section id="blog" class="blog">
        <div class="container">
            {% if messages %}
                <div class="alert alert-success">
                    {% for message in messages %}
                        {{ message }}
                    {% endfor %}
                </div>
            {% endif %}
            <div class="article-edit-form"><h4>Новая статья</h4>
                <form action="" method="post">{% csrf_token %}
                    {{ form.media | safe }}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">Создать</button>
                </form>
            </div>
        </div>
    </section>
{% endblock content %}

articleapp/templates/articles_list.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block css %}
    <link href="{% static 'adminapp/css/admin_style.css' %}" rel="stylesheet">
{% endblock css %}

{% block content %}

    <section id="blog" class="blog">
        <div class="container">

            {% for article in object_list %}
                <article class="entry">
                    <h2 class="entry-title">
                        <a href="{% url 'article:detail' article.pk %}">{{ article.title }}</a>
                    </h2>
                    <div class="entry-meta">
                        <ul>
                            <li class="d-flex align-items-center"><i class="bi bi-person"></i> <a
                                    href="{% url 'auth:profile' article.author.pk %}">{{ article.author }}</a></li>
                            <li class="d-flex align-items-center"><i class="bi bi-clock"></i> <a
                                    href="{% url 'article:detail' article.pk %}">
                                {% if article.publication_date %}
                                <time datetime="2020-01-01">{{ article.publication_date }}</time>
                                {% else %}
                                <time datetime="2020-01-01">{{ article.created }}</time>
                                {% endif %}
                            </a></li>
                            <li class="d-flex align-items-center"><i class="bi bi-chat-dots"></i> <a
                                    href="{% url 'article:detail' article.pk %}">Комментариев: {{ article.comments_articles.all.count }}</a>
                            </li>
                            <li class="d-flex align-items-center"><i class="bi bi-hand-thumbs-up"></i> <a
                                    href="{% url 'article:detail' article.pk %}">{{ article.liked.all.count }}</a>
                            </li>
                            <li class="d-flex align-items-center"><i class="bi bi-bar-chart"></i> <a
                                    href="{% url 'article:detail' article.pk %}">Рейтинг: {{ article.rating }}</a>
                            </li>

                        </ul>
                    </div>

                    <div class="entry-content">
                        <p>
                            {{ article.content | safe | truncatechars_html:500 }}
                        </p>
                        <div class="read-more">
                            <a href="{% url 'article:detail' article.pk %}">Дальше</a>
                        </div>
                    </div>

                </article>
                <!-- End blog entry -->
            {% endfor %}
            {% include "paginator.html" %}

        </div>
    </section><!-- End Blog Section -->
{% endblock content %}

articleapp/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Статья</title>
</head>
<body>

</body>
</html>

articleapp/templates/category.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block css %}
    <script src="https://netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
    <script src="https://code.jquery.com/jquery-1.11.1.min.js"></script>
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">
{% endblock css %}

{% block content %}
<section id="breadcrumbs" class="breadcrumbs">
      <div class="container">
        <h4>
            Статьи в категории: {{ category.name }} - {{ article_list|length }}
            шт.
        </h4>
      </div>
</section>
<div id="blog" class="blog">
<div class="container" data-aos="fade-up">
    <div class="row">        
        {% for article in article_list %}
            <article class="entry">

                <div class="entry-img">
                    <img src="{{ article.image }}" alt="" class="img-fluid" width="100%">
                </div>

                <h2 class="entry-title">
                    <a href="{% url 'article:detail' article.pk %}">
                        {{ article.title }}
                    </a>
                </h2>

                <h5>
                    <span>Категория: {{ article.category }}</span>
                </h5>

                <div class="entry-meta">
                    <ul>
                        <li class="d-flex align-items-center"><i class="bi bi-person"></i>
                            <span>Автор:

                                <a href="{% url 'auth:profile' article.author.pk %}"
				                           target="_blank"
                                   style="color: dodgerblue"
                                   class="">

                                    {{ article.author }}
                                </a>
                            </span>
                        </li>

                        <li class="d-flex align-items-center"><i class="bi bi-clock"></i>
                            <a>{{ article.publication_date }}</a></li>
                        <li class="d-flex align-items-center"><i class="bi bi-chat-dots"></i>
                            <a>Комментариев: {{article.comments_articles.all.count }}</a>
                        </li>
                        <li class="d-flex align-items-center"><i class="bi bi-bar-chart"></i> <a
                                 href="{% url 'article:detail' article.pk %}">Рейтинг: {{ article.rating }}</a>
                        </li>
                    </ul>
                </div>

                <div class="entry-content">
                    <div class="read-more">
                        <a href="{% url 'article:detail' article.pk %}">Читать далее</a>
                    </div>
                </div>
              
            </article>
        {% endfor %}
        {% include 'adminapp/includes/pagination.html' %}
        </div>
    </div>
</div>
</div>
{% endblock content %}

articleapp/templates/paginator.html
<div class="blog-pagination">
    <ul class="justify-content-center">
        {% if page_obj.number != 1 %}
            <li>
                <a href="?page=1">1</a>
            </li>
        {% endif %}
        {% if page_obj.has_previous and page_obj.previous_page_number != 1%}
            <li>
                <a href="?page={{ page_obj.previous_page_number }}">
                    {{ page_obj.previous_page_number }}
                </a>
            </li>
        {% endif %}

        <li class="active">
            <a>{{page_obj.number}}</a>
        </li>
      
        {% if page_obj.has_next %}
            <li>
                <a href="?page={{ page_obj.next_page_number }}">
                    {{ page_obj.next_page_number }}
                </a>
            </li>
        {% endif %}
        {% if page_obj.has_next and page_obj.next_page_number != page_obj.paginator.num_pages %}
            <li>
                <a href="?page={{ page_obj.paginator.num_pages }}">
                    {{ page_obj.paginator.num_pages }}
                </a>
            </li>
        {% endif %}
    </ul>
</div>